iotex monster go add token
iotexproject/iotex-token-metadata pull request #101
Opened 2022-01-21 16:34 UTC by bcigame

## Token Information

- **Project official website**: https://...

- **Project official social**: https://...

## Verification of Token

- [ ] verify of your token smart contract on iotexscan.
- [ ] add your token address to your website and list here: https://

2022-02-14 05:08 UTC, guo commented
Please resolve the conflict.

2022-02-21 08:28 UTC, bcigame commented
> Please resolve the conflict.
Already processed please review

2022-03-08 03:36 UTC, ququzone approved these changes

2022-03-08 03:42 UTC, ququzone requested changes
Please add your token address to your website.

2022-03-08 05:35 UTC, ququzone approved these changes

2022-03-08 05:35 UTC, merged