Update XIM Token
iotexproject/iotex-token-metadata pull request #114
Opened 2022-03-14 02:29 UTC by xDollarFi

## Token Information

- **Project official website**: http://xdollar.fi/

- **Project official social**: https://twitter.com/xdollarfi

## Verification of Token

- [ ] verify of your token smart contract on iotexscan.
- [ ] add your token address to your website and list here: https://docs.xdollar.fi/

2022-03-14 03:41 UTC, uu-z requested changes

2022-03-14 03:41 UTC, uu-z commented on token-metadata.json
> +  "io1kcshra7xxac8ex7c6vqvjgfhc3lkxpj7ac4rkl": {
please verify the new contract on 
https://iotexscan.io/address/io1kcshra7xxac8ex7c6vqvjgfhc3lkxpj7ac4rkl?format=0x#readContract

2022-03-16 05:37 UTC, xDollarFi commented on token-metadata.json
> +  "io1kcshra7xxac8ex7c6vqvjgfhc3lkxpj7ac4rkl": {
verified. thx

2022-03-18 01:05 UTC, uu-z approved these changes

2022-03-18 01:06 UTC, merged